<?php
/** @var $this FeatureCard */
use ProtectedNet\FrontendTest\Components\FeatureCard\FeatureCard;
?>

<?php if($this->getIcon()): ?>
  <div class="<?= $this->getElementName('icon') ?>">
    <?= $this->getIcon()->produceSafeHTML() ?>
  </div>
<?php endif; ?>

<?php if($this->getPercent()):
    if (($this->getPercent() == "25")):?>
    <div class="feature-card__percentStyle twenty-five-base">
        <p class="twenty-five-percent"><?= $this->getPercent()?>%</p>
    </div>
    <?php endif;
    if (($this->getPercent() == "50")):?>
    <div class="feature-card__percentStyle fifty-five-base">
        <p class="fifty-five-percent"><?= $this->getPercent()?>%</p>
    </div>
    <?php endif;
        if (($this->getPercent() == "75")):?>
    <div class="feature-card__percentStyle seventy-five-base">
        <p class="seventy-five-percent"><?= $this->getPercent()?>%</p>
    </div>
    <?php endif;
        if (($this->getPercent() == "100")):?>
    <div class="feature-card__percentStyle hundred-base">
        <p class="hundred-percent"><?= $this->getPercent()?>%</p>
    </div>
    <?php endif; ?>
<?php endif; ?>

<div class="<?= $this->getElementName('content') ?>">
  <?php if($this->getTitle()): ?>
    <h4 class="feature-card__title"><?= $this->getTitle() ?></h4>
  <?php endif; ?>

  <?php if($this->getSubtitle()): ?>
    <h5 class="feature-card__subtitle"><?= $this->getSubtitle() ?></h5>
  <?php endif; ?>

  <?php if($this->getDescription()): ?>
    <p class="feature-card__description"><?= $this->getDescription() ?></p>
  <?php endif; ?>

</div>
