<?php
/** @var $this SlideThree */

use ProtectedNet\FrontendTest\Components\Button\Button;
use ProtectedNet\FrontendTest\Partials\HeroContent\SlideThree\SlideThree;

?>


<div class="<?= $this->getElementName('background-img') ?>" style="background-image: url('<?= $this->getImg('slider-3.jpg') ?>');"></div>


<div class="<?= $this->getElementName('content') ?>">
    <div class="grid-container <?= $this->getElementName('job-post-holder') ?>">
        <div class="grid-x">
            <div class="cell">
                <h1 class="<?= $this->getElementName('title') ?>">Looking for <strong>new</strong> candidates?</h1>
            </div>
            <div class="medium-5 medium-offset-1">
                <p class="<?= $this->getElementName('job-post-desc') ?>">Are you a business looking to expand and find the best possible candidates for your role? If so post your job opportunity here and we will handle the rest</p>
            </div>
            <div class="medium-4 medium-offset-1 <?= $this->getElementName('job-post-button') ?>">
                <?= Button::i('Get started now!')->iconRight("<i class='fa fa-arrow-right'></i>") ?>
            </div>
        </div>
    </div>
</div>
