<?php
/** @var $this SlideThree */

use ProtectedNet\FrontendTest\Components\Button\Button;
use ProtectedNet\FrontendTest\Partials\HeroContent\SlideThree\SlideThree;

?>


<div class="<?= $this->getElementName('background-img') ?>" style="background-image: url('<?= $this->getImg('slider-3.jpg') ?>');"></div>


<div class="<?= $this->getElementName('content') ?>">
    <div class="grid-container">
        <div class="grid-x">
            <div class="cell">
                <h1 class="<?= $this->getElementName('title') ?>"><strong>Kick-starting</strong></h1>
                <h1 class="<?= $this->getElementName('title-second') ?> text-right"> careers</h1>
            </div>
        </div>

        <div class="grid-x grid-padding-y grid-padding-x <?= $this->getElementName('cta-holder') ?>">
            <div class="cell medium-offset-1 medium-10 text-center">
                <?= Button::i('Hear from our customers!')->iconRight("<i class='fa fa-chevron-right'></i>") ?>
            </div>
        </div>
    </div>
</div>
