<?php
/** @var $this Price */
use ProtectedNet\FrontendTest\Components\PriceComp\Price;
use ProtectedNet\FrontendTest\Components\Button\Button;
?>




<div class="<?= $this->getElementName('content') ?>">

    <div class="<?= $this->getElementName('price-cont') ?> text-center">
        <div class="<?= $this->getElementName('top-price') ?>">
            <?php if($this->getTitle()): ?>
                <h4 class="<?= $this->getElementName('title') ?>"><?= $this->getTitle() ?></h4>
            <?php endif; ?>

            <?php if($this->getPrice()): ?>
                <h2 class="<?= $this->getElementName('price') ?>"><?= $this->getPrice() ?></h2>
            <?php endif; ?>

            <?php if($this->getPrice()): ?>
                <p class="<?= $this->getElementName('subtitle') ?>"><?= $this->getSubtitle() ?></p>
            <?php endif; ?>
        </div>
        <div class="<?= $this->getElementName('bottom-price') ?>">
            <?php if($this->getDescription()): ?>
                <p class="<?= $this->getElementName('description') ?>"><?= $this->getDescription() ?></p>
            <?php endif; ?>
            <?= Button::i('Shop Now!')->iconRight("<i class='fa fa-chevron-right'></i>")->priceAnimate()->small()?>
        </div>
    </div>
</div>
